# Generated by Django 2.1.5 on 2019-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logEntry',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='Commit ID')),
                ('start', models.CharField(max_length=1000, verbose_name='Start')),
                ('stop', models.CharField(max_length=1000, verbose_name='Stop')),
                ('status', models.CharField(max_length=1000, verbose_name='Status')),
            ],
        ),
    ]
