# Generated by Django 2.1.5 on 2019-02-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logDbApp', '0002_remove_logentry_stop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='id',
            new_name='commit_id',
        ),
    ]
